from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.views.generic import TemplateView, RedirectView


from accounts.views import LoginView, RegisterView, GuestRegisterView
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_createview
from carts.views import (
    cart_detail_api_view,
    cart_changed_state,
    cart_quantity_change,
    cart_shipping_change,
    paypal_success,
    cart_overlay_remove_item,
    delivery_options,
)
from filebrowser.sites import site
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from orders.views import email_customer
from shipping.views import get_postcode_price
from xero_app.views import cart_invoice_create, process_callback_view #cart_invoice_create
from . import views
from .views import error_404, error_500, error_500_test

from django.conf.urls import handler500, handler404

from .sitemaps import ProductSitemap, StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'product': ProductSitemap,
}


urlpatterns = [
    # Third party apps
    # Django JET URLS
    path('jet/', include('jet.urls', 'jet')),
    # Django JET dashboard URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    # TinyMCE
    url(r'^tinymce/', include('tinymce.urls')),
    # Filebrowser
    url(r'^admin/filebrowser/', site.urls),

    url(r'^\.well-known/pki-validation/FD4AEF98B396F9D92FA06621D3D6CDAC\.txt$', TemplateView.as_view(template_name="verify.txt", content_type='text/plain')),

    # TEST URLS
    # TEST 500 ERROR:
    path('500/', error_500_test, name='500-error-test'),

    # API
    # Cart
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('cart/state-changed/', cart_changed_state, name='changed-state'),
    path('cart/quantity-changed/', cart_quantity_change, name='changed-quantity'),
    path('cart/shipping-changed/', cart_shipping_change, name='changed-shipping'),
    path('cart/checkout/paypal-success', paypal_success, name='paypal-success'),
    path('cart/delivery-options/', delivery_options, name='delivery-options'),
    path('cart-overlay/remove-item', cart_overlay_remove_item, name='cart-overlay-remove-item'),
    # Xero
    path('xero/create-invoice', cart_invoice_create, name='xero-create-invoice'),
    path('xero/callback-view', process_callback_view, name='xero-callback-view'),

    # sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # Robots.txt
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
    path('test.html', TemplateView.as_view(template_name="email/order_confirmation.html")),

    # Admin Pages
    path('admin/', admin.site.urls),
    # Home Page
    path('', views.home_page, name='home'),
    path('about/', views.about_page, name='about'),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include("accounts.urls", namespace='account')),
    path('accounts/', include("accounts.passwords.urls")),

    # Address related
    # path('address/', RedirectView.as_view(url='/addresses')),
    # path('addresses/', AddressListView.as_view(), name='addresses'),
    # path('addresses/create/', AddressCreateView.as_view(), name='address-create'),
    # re_path('addresses/(?P<pk>\d+)/',
    #         AddressUpdateView.as_view(), name='address-update'),

    # Analytic related
    path('analytics/sales/', SalesView.as_view(), name='sales-analytics'),
    path('analytics/sales/data/', SalesAjaxView.as_view(),
         name='sales-analytics-data'),

    path('contact/', views.contact_page, name='contact'),
    path('login/', LoginView.as_view(), name='login'),
    # path('checkout/address/create/', checkout_address_create_view,
    #      name='checkout_address_create'),
    # path('checkout/address/reuse/', checkout_address_reuse_view,
    #      name='checkout_address_reuse'),
    path('register/guest/', GuestRegisterView.as_view(), name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # AJAX send email to customer from admin email page
    path('email-customer/', email_customer, name='email-customer'),

    # CART URLS
    path('cart/', include("carts.urls", namespace='cart')),
    # FOOTER URLS
    path('', include("footer_content.urls", namespace='footer_content')),

    # AJAX Post Code Shipping Price
    path('get_post_code/', get_postcode_price, name='api-post-code'),

    path('billing/payment-method', payment_method_view,
         name='billing-payment-method'),
    path('billing/payment-method/create/', payment_method_createview,
         name='billing-payment-method-endpoint'),
    path('register/', RegisterView.as_view(), name='register'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('orders/', include("orders.urls", namespace='orders')),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(),
         name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(),
         name='webhooks-mailchimp'),

    # Site map
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),


    # Old URL's redirecting to new urls
    # path('old-url/', views.url_update_page, name='urls_update'),
    path('roofing-fasteners/17-colorbond-roofing-screws-12-x-50-multifix.html', RedirectView.as_view(url='/products/colorbond-roof-screws-12-x-50-multifix')),
    path('roofing-fasteners/17-colorbond-roofing-screws-12-x-50-multifix.html', RedirectView.as_view(url='/products/colorbond-roof-screws-12-x-50-multifix')),
    path('roofing-fasteners/17-colorbond-roofing-screws-12-x-50-multifix.html', RedirectView.as_view(url='/products/colorbond-roof-screws-12-x-50-multifix')),
    path('roofing-fasteners/299-colorbond-roofing-screws-12-x-50-type-17.html', RedirectView.as_view(url='/products/-colorbond-roofing-screws-12-x-50-type-17')),
    path('roofing-fasteners/299-colorbond-roofing-screws-12-x-50-type-17.html', RedirectView.as_view(url='/products/-colorbond-roofing-screws-12-x-50-type-17')),
    path('roofing-fasteners/299-colorbond-roofing-screws-12-x-50-type-17.html', RedirectView.as_view(url='/products/-colorbond-roofing-screws-12-x-50-type-17')),
    path('roofing-fasteners/32-12-x-25-screws-colorbond.html', RedirectView.as_view(url='/products/12-x-25-screws-colorbond')),
    path('roofing-fasteners/32-12-x-25-screws-colorbond.html', RedirectView.as_view(url='/products/12-x-25-screws-colorbond')),
    path('roofing-fasteners/32-12-x-25-screws-colorbond.html', RedirectView.as_view(url='/products/12-x-25-screws-colorbond')),
    path('roofing-fasteners/301-colorbond-roofing-screws-12-x-65-t17.html', RedirectView.as_view(url='/products/colorbond-roofing-screws-12-x-65-t17')),
    path('roofing-fasteners/301-colorbond-roofing-screws-12-x-65-t17.html', RedirectView.as_view(url='/products/colorbond-roofing-screws-12-x-65-t17')),
    path('roofing-fasteners/301-colorbond-roofing-screws-12-x-65-t17.html', RedirectView.as_view(url='/products/colorbond-roofing-screws-12-x-65-t17')),
    path('roofing-fasteners/112-colorbond-screws-10-x-16-sf.html', RedirectView.as_view(url='/products/colorbond-screws-10-x-16-sf')),
    path('roofing-fasteners/112-colorbond-screws-10-x-16-sf.html', RedirectView.as_view(url='/products/colorbond-screws-10-x-16-sf')),
    path('roofing-fasteners/112-colorbond-screws-10-x-16-sf.html', RedirectView.as_view(url='/products/colorbond-screws-10-x-16-sf')),
    path('roofing-tools/28-magnetic-516-hex-socket-42mm.html', RedirectView.as_view(url='/products/magnetic-516-hex-socket-42mm')),
    path('roofing-tools/28-magnetic-516-hex-socket-42mm.html', RedirectView.as_view(url='/products/magnetic-516-hex-socket-42mm')),
    path('roofing-tools/28-magnetic-516-hex-socket-42mm.html', RedirectView.as_view(url='/products/magnetic-516-hex-socket-42mm')),
    path('polycarbonate/146-corrugated-roofing-sheets.html', RedirectView.as_view(url='/products/polycarbonate-corrugated-roofing-sheets')),
    path('home/412-polycarbonate-corrugated-roofing-sheets-nsw.html', RedirectView.as_view(url='/products/polycarbonate-corrugated-roofing-sheets')),
    path('home/413-polycarbonate-corrugated-roofing-sheets-brisbane-.html', RedirectView.as_view(url='/products/polycarbonate-corrugated-roofing-sheets')),
    path('polycarbonate/148-5-rib-roofing-sheets-trimdek.html', RedirectView.as_view(url='/products/5-rib-roofing-sheets-trimdek')),
    path('polycarbonate/416-5-rib-polycarbonate-roofing-sheets-trimdek-nsw.html', RedirectView.as_view(url='/products/5-rib-roofing-sheets-trimdek')),
    path('polycarbonate/417-5-rib-polycarbonate-roofing-sheets-trimdek-brisbane-.html', RedirectView.as_view(url='/products/5-rib-roofing-sheets-trimdek')),
    path('home/422-corrugated-level-2-solafrost-polycarbonate-roofing.html', RedirectView.as_view(url='/products/corrugated-level-2-solafrost-polycarbonate-roofing')),
    path('polycarbonate/149-polycarbonate-self-cutting-roofing-screw.html', RedirectView.as_view(url='/products/polycarbonate-self-cutting-roofing-screw')),
    path('polycarbonate/149-polycarbonate-self-cutting-roofing-screw.html', RedirectView.as_view(url='/products/polycarbonate-self-cutting-roofing-screw')),
    path('polycarbonate/149-polycarbonate-self-cutting-roofing-screw.html', RedirectView.as_view(url='/products/polycarbonate-self-cutting-roofing-screw')),
    path('roofing-fasteners/31-polycarbonate-screw-and-dome-seal-12-x-50.html', RedirectView.as_view(url='/products/polycarbonate-screw-and-dome-seal-12-x-50')),
    path('roofing-fasteners/31-polycarbonate-screw-and-dome-seal-12-x-50.html', RedirectView.as_view(url='/products/polycarbonate-screw-and-dome-seal-12-x-50')),
    path('roofing-fasteners/31-polycarbonate-screw-and-dome-seal-12-x-50.html', RedirectView.as_view(url='/products/polycarbonate-screw-and-dome-seal-12-x-50')),
    path('roofing-fasteners/34-colorbond-pop-rivets-as4-3.html', RedirectView.as_view(url='/products/colorbond-pop-rivets-as4-3')),
    path('roofing-fasteners/34-colorbond-pop-rivets-as4-3.html', RedirectView.as_view(url='/products/colorbond-pop-rivets-as4-3')),
    path('roofing-fasteners/34-colorbond-pop-rivets-as4-3.html', RedirectView.as_view(url='/products/colorbond-pop-rivets-as4-3')),
    path('home/419-double-ended-drill-bit-18-no-30.html', RedirectView.as_view(url='/products/double-ended-drill-bit-18-no-30')),
    path('home/419-double-ended-drill-bit-18-no-30.html', RedirectView.as_view(url='/products/double-ended-drill-bit-18-no-30')),
    path('home/419-double-ended-drill-bit-18-no-30.html', RedirectView.as_view(url='/products/double-ended-drill-bit-18-no-30')),
    path('roofing-tools/51-rivet-gun-lobster-hr-200.html', RedirectView.as_view(url='/products/rivet-gun-lobster-hr-200')),
    path('roofing-tools/51-rivet-gun-lobster-hr-200.html', RedirectView.as_view(url='/products/rivet-gun-lobster-hr-200')),
    path('roofing-tools/51-rivet-gun-lobster-hr-200.html', RedirectView.as_view(url='/products/rivet-gun-lobster-hr-200')),
    path('roofing-tools/44-tin-snips-left-cut-straight-.html', RedirectView.as_view(url='/products/tin-snips-left-right-cut-straight')),
    path('roofing-tools/44-tin-snips-left-cut-straight-.html', RedirectView.as_view(url='/products/tin-snips-left-right-cut-straight')),
    path('roofing-tools/44-tin-snips-left-cut-straight-.html', RedirectView.as_view(url='/products/tin-snips-left-right-cut-straight')),
    path('victoria/9-corrugated-colorbond-roofing-sheets.html', RedirectView.as_view(url='/products/corrugated-colorbond-roofing-sheets')),
    path('victoria/335-48-corrugated-iron-colorbond-roofing-sheets.html', RedirectView.as_view(url='/products/48-corrugated-iron-colorbond-roofing-sheets')),
    path('victoria/10-corrugated-iron-zincalume-roofing-sheets.html', RedirectView.as_view(url='/products/corrugated-iron-zincalume-roofing-sheets')),
    path('victoria/336-corrugated-iron-zincalume-roofing-sheets-48bmt.html', RedirectView.as_view(url='/products/corrugated-iron-zincalume-roofing-sheets-48bmt')),
    path('victoria/13-trimdek-colorbond-roofing.html', RedirectView.as_view(url='/products/trimdek-colorbond-roofing')),
    path('victoria/18-trimdek-zincalume-roofing-sheets.html', RedirectView.as_view(url='/products/trimdek-zincalume-roofing-sheets')),
    path('victoria/344-48-bmt-trimdek-colorbond-roofing-sheets.html', RedirectView.as_view(url='/products/48-bmt-trimdek-colorbond-roofing-sheets')),
    path('victoria/378-48-bmt-trimdek-zincalume-roof-sheets.html', RedirectView.as_view(url='/products/48-bmt-trimdek-zincalume-roof-sheets')),
    path('victoria/15-klip-lok-700-colorbond-roofing-hi-strength-.html', RedirectView.as_view(url='/products/klip-lok-700-colorbond-roofing-hi-strength-')),
    path('victoria/19-klip-lok-700-zincalume-roofing-sheets.html', RedirectView.as_view(url='/products/klip-lok-700-zincalume-roofing-sheets')),
    path('victoria/402-klip-lok-700-colorbond-roofing-48bmt.html', RedirectView.as_view(url='/products/klip-lok-700-colorbond-roofing-48bmt')),
    path('victoria/431-48-bmt-klip-lok-zincalume-roofing.html', RedirectView.as_view(url='/products/48-bmt-klip-lok-zincalume-roofing')),
    path('home/428-colorbond-standing-seam-cladding.html', RedirectView.as_view(url='/products/colorbond-standing-seam-cladding-330')),
    path('home/427-colorbond-standing-seam-cladding.html', RedirectView.as_view(url='/products/colorbond-standing-seam-cladding')),
    path('roofing-fasteners/426-standing-seam-clip-25mm.html', RedirectView.as_view(url='/products/standing-seam-clip-25mm')),
    path('home/429-draco-single-lock-seamer-k8-210mm-standing-seam-vic.html', RedirectView.as_view(url='/products/draco-single-lock-seamer-k8-210mm-standing-seam-vic')),
    path('victoria/398-matt-colorbond-corrugated-iron-roofing.html', RedirectView.as_view(url='/products/matt-colorbond-corrugated-iron-roofing')),
    path('fascia-accessories/72-fascia-spring-clip.html', RedirectView.as_view(url='/products/fascia-spring-clip')),
    path('fascia-accessories/72-fascia-spring-clip.html', RedirectView.as_view(url='/products/fascia-spring-clip')),
    path('fascia-accessories/72-fascia-spring-clip.html', RedirectView.as_view(url='/products/fascia-spring-clip')),
    path('victoria/124-colorbond-fascia-.html', RedirectView.as_view(url='/products/colorbond-fascia-')),
    path('victoria/125-zincalume-fascia-.html', RedirectView.as_view(url='/products/zincalume-fascia-')),
    path('new-south-wales/136-colorbond-fascia.html', RedirectView.as_view(url='/products/colorbond-fascia')),
    path('new-south-wales/137-zincalume-fascia-nsw.html', RedirectView.as_view(url='/products/zincalume-fascia-nsw')),
    path('queensland/195-colorbond-fascia.html', RedirectView.as_view(url='/products/colorbond-fascia-qld')),
    path('queensland/196-zincalume-fascia.html', RedirectView.as_view(url='/products/zincalume-fascia-qld')),
    path('downpipe-accessories/258-100-x-50-downpipe-clips-zincalume.html', RedirectView.as_view(url='/products/Downpipe-Clip-COLORBOND-ZINCALUME')),
    path('downpipe-accessories/258-100-x-50-downpipe-clips-zincalume.html', RedirectView.as_view(url='/products/Downpipe-Clip-COLORBOND-ZINCALUME')),
    path('downpipe-accessories/258-100-x-50-downpipe-clips-zincalume.html', RedirectView.as_view(url='/products/Downpipe-Clip-COLORBOND-ZINCALUME')),
    path('roofing-fasteners/37-bugle-head-screws-7-x-25-t17.html', RedirectView.as_view(url='/products/bugle-head-screws-7-x-25-t17')),
    path('roofing-fasteners/37-bugle-head-screws-7-x-25-t17.html', RedirectView.as_view(url='/products/bugle-head-screws-7-x-25-t17')),
    path('roofing-fasteners/37-bugle-head-screws-7-x-25-t17.html', RedirectView.as_view(url='/products/bugle-head-screws-7-x-25-t17')),
    path('foam-strips/56-foam-infill-end-closure-strip-corrugated-profile-.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-corrugated-profile')),
    path('foam-strips/56-foam-infill-end-closure-strip-corrugated-profile-.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-corrugated-profile')),
    path('foam-strips/56-foam-infill-end-closure-strip-corrugated-profile-.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-corrugated-profile')),
    path('foam-strips/54-infill-end-closure-strip-trimdek-top-profile.html', RedirectView.as_view(url='/products/infill-end-closure-strip-trimdek-top-profile')),
    path('foam-strips/54-infill-end-closure-strip-trimdek-top-profile.html', RedirectView.as_view(url='/products/infill-end-closure-strip-trimdek-top-profile')),
    path('foam-strips/54-infill-end-closure-strip-trimdek-top-profile.html', RedirectView.as_view(url='/products/infill-end-closure-strip-trimdek-top-profile')),
    path('foam-strips/53-infill-end-closure-strip-trimdek-profile-bottom.html', RedirectView.as_view(url='/products/infill-end-closure-strip-trimdek-profile-bottom')),
    path('foam-strips/53-infill-end-closure-strip-trimdek-profile-bottom.html', RedirectView.as_view(url='/products/infill-end-closure-strip-trimdek-profile-bottom')),
    path('foam-strips/53-infill-end-closure-strip-trimdek-profile-bottom.html', RedirectView.as_view(url='/products/infill-end-closure-strip-trimdek-profile-bottom')),
    path('foam-strips/331-infill-end-closure-klip-lok-top-profile-.html', RedirectView.as_view(url='/products/infill-end-closure-klip-lok-top-profile')),
    path('foam-strips/331-infill-end-closure-klip-lok-top-profile-.html', RedirectView.as_view(url='/products/infill-end-closure-klip-lok-top-profile')),
    path('foam-strips/331-infill-end-closure-klip-lok-top-profile-.html', RedirectView.as_view(url='/products/infill-end-closure-klip-lok-top-profile')),
    path('foam-strips/332-foam-infill-end-closure-strip-klip-lok-bottom-profile-.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-klip-lok-bottom-prof')),
    path('foam-strips/332-foam-infill-end-closure-strip-klip-lok-bottom-profile-.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-klip-lok-bottom-prof')),
    path('foam-strips/332-foam-infill-end-closure-strip-klip-lok-bottom-profile-.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-klip-lok-bottom-prof')),
    path('polycarbonate/397-polycarbonate-roofing-screw-dome-seal-14-x-65.html', RedirectView.as_view(url='/products/polycarbonate-roofing-screw-dome-seal-14-x-65')),
    path('polycarbonate/397-polycarbonate-roofing-screw-dome-seal-14-x-65.html', RedirectView.as_view(url='/products/polycarbonate-roofing-screw-dome-seal-14-x-65')),
    path('polycarbonate/397-polycarbonate-roofing-screw-dome-seal-14-x-65.html', RedirectView.as_view(url='/products/polycarbonate-roofing-screw-dome-seal-14-x-65')),
    path('roofing-fasteners/303-plain-roofing-screws-12-x-40-t17.html', RedirectView.as_view(url='/products/-plain-roofing-screws-12-x-40-t17')),
    path('roofing-fasteners/303-plain-roofing-screws-12-x-40-t17.html', RedirectView.as_view(url='/products/-plain-roofing-screws-12-x-40-t17')),
    path('roofing-fasteners/303-plain-roofing-screws-12-x-40-t17.html', RedirectView.as_view(url='/products/-plain-roofing-screws-12-x-40-t17')),
    path('ridge/79-colorbond-roll-top-ridge-capping-.html', RedirectView.as_view(url='/products/colorbond-roll-top-ridge-capping-')),
    path('gutter-guard/115-gutter-guard-leafless-plain.html', RedirectView.as_view(url='/products/gutter-guard-leafless-plain')),
    path('gutter-guard/115-gutter-guard-leafless-plain.html', RedirectView.as_view(url='/products/gutter-guard-leafless-plain')),
    path('gutter-guard/115-gutter-guard-leafless-plain.html', RedirectView.as_view(url='/products/gutter-guard-leafless-plain')),
    path('polycarbonate/151-anti-noise-tape-polycarbonate-roofing-24m-roll.html', RedirectView.as_view(url='/products/anti-noise-tape-polycarbonate-roofing-24m-roll')),
    path('polycarbonate/151-anti-noise-tape-polycarbonate-roofing-24m-roll.html', RedirectView.as_view(url='/products/anti-noise-tape-polycarbonate-roofing-24m-roll')),
    path('polycarbonate/151-anti-noise-tape-polycarbonate-roofing-24m-roll.html', RedirectView.as_view(url='/products/anti-noise-tape-polycarbonate-roofing-24m-roll')),
    path('accessories/49-touch-up-paint-colorbond-spray-can.html', RedirectView.as_view(url='/products/touch-up-paint-colorbond-spray-can')),
    path('accessories/52-fast-flash-280mm-wide-x-50m-roll-.html', RedirectView.as_view(url='/products/fast-flash-280mm-wide-x-50m-roll-')),
    path('accessories/52-fast-flash-280mm-wide-x-50m-roll-.html', RedirectView.as_view(url='/products/fast-flash-280mm-wide-x-50m-roll-')),
    path('accessories/52-fast-flash-280mm-wide-x-50m-roll-.html', RedirectView.as_view(url='/products/fast-flash-280mm-wide-x-50m-roll-')),
    path('fascia-accessories/382-metal-fascia-spacer-insert.html', RedirectView.as_view(url='/products/metal-fascia-spacer-insert')),
    path('fascia-accessories/382-metal-fascia-spacer-insert.html', RedirectView.as_view(url='/products/metal-fascia-spacer-insert')),
    path('fascia-accessories/382-metal-fascia-spacer-insert.html', RedirectView.as_view(url='/products/metal-fascia-spacer-insert')),
    path('fascia-accessories/74-splice-plate-joiner-to-suit-metal-fascia.html', RedirectView.as_view(url='/products/splice-plate-joiner-to-suit-metal-fascia')),
    path('fascia-accessories/74-splice-plate-joiner-to-suit-metal-fascia.html', RedirectView.as_view(url='/products/splice-plate-joiner-to-suit-metal-fascia')),
    path('fascia-accessories/74-splice-plate-joiner-to-suit-metal-fascia.html', RedirectView.as_view(url='/products/splice-plate-joiner-to-suit-metal-fascia')),
    path('fascia-accessories/73-fascia-over-strap.html', RedirectView.as_view(url='/products/fascia-over-strap')),
    path('fascia-accessories/73-fascia-over-strap.html', RedirectView.as_view(url='/products/fascia-over-strap')),
    path('fascia-accessories/73-fascia-over-strap.html', RedirectView.as_view(url='/products/fascia-over-strap')),
    path('fascia-accessories/71-fascia-standard-rafter-clip-bracket.html', RedirectView.as_view(url='/products/fascia-standard-rafter-clip-bracket')),
    path('fascia-accessories/71-fascia-standard-rafter-clip-bracket.html', RedirectView.as_view(url='/products/fascia-standard-rafter-clip-bracket')),
    path('fascia-accessories/71-fascia-standard-rafter-clip-bracket.html', RedirectView.as_view(url='/products/fascia-standard-rafter-clip-bracket')),
    path('barge-capping/84-colorbond-capping-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-capping-roof-flashing')),
    path('barge-capping/84-colorbond-capping-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-capping-roof-flashing')),
    path('barge-capping/84-colorbond-capping-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-capping-roof-flashing')),
    path('barge-capping/466-barge-capping-roof-flashing-colorbond-40mm.html', RedirectView.as_view(url='/products/barge-capping-roof-flashing-colorbond-40mm')),
    path('barge-capping/466-barge-capping-roof-flashing-colorbond-40mm.html', RedirectView.as_view(url='/products/barge-capping-roof-flashing-colorbond-40mm')),
    path('barge-capping/466-barge-capping-roof-flashing-colorbond-40mm.html', RedirectView.as_view(url='/products/barge-capping-roof-flashing-colorbond-40mm')),
    path('barge-capping/85-colorbond-roof-flashing-trimdek-.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-trimdek-')),
    path('barge-capping/85-colorbond-roof-flashing-trimdek-.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-trimdek-')),
    path('barge-capping/85-colorbond-roof-flashing-trimdek-.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-trimdek-')),
    path('barge-capping/339-colorbond-roof-flashing-suit-klip-lok.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-suit-klip-lok')),
    path('barge-capping/339-colorbond-roof-flashing-suit-klip-lok.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-suit-klip-lok')),
    path('barge-capping/339-colorbond-roof-flashing-suit-klip-lok.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-suit-klip-lok')),
    path('barge-capping/497-colorbond-roof-flashing-90mm.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-90mm')),
    path('barge-capping/497-colorbond-roof-flashing-90mm.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-90mm')),
    path('barge-capping/497-colorbond-roof-flashing-90mm.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-90mm')),
    path('flashings/515-colorbond-right-angle-flashing-50-x-50.html', RedirectView.as_view(url='/products/colorbond-right-angle-flashing-50-x-50')),
    path('flashings/515-colorbond-right-angle-flashing-50-x-50.html', RedirectView.as_view(url='/products/colorbond-right-angle-flashing-50-x-50')),
    path('flashings/515-colorbond-right-angle-flashing-50-x-50.html', RedirectView.as_view(url='/products/colorbond-right-angle-flashing-50-x-50')),
    path('foam-strips/55-foam-infill-end-closure-strip-greca-profile.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-greca-profile')),
    path('foam-strips/55-foam-infill-end-closure-strip-greca-profile.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-greca-profile')),
    path('foam-strips/55-foam-infill-end-closure-strip-greca-profile.html', RedirectView.as_view(url='/products/foam-infill-end-closure-strip-greca-profile')),
    path('insulation/41-double-sided-tape-25mm-wide-.html', RedirectView.as_view(url='/products/double-sided-tape-25mm-wide')),
    path('insulation/41-double-sided-tape-25mm-wide-.html', RedirectView.as_view(url='/products/double-sided-tape-25mm-wide')),
    path('insulation/41-double-sided-tape-25mm-wide-.html', RedirectView.as_view(url='/products/double-sided-tape-25mm-wide')),
    path('fascia-accessories/69-fascia-internal-cover-caps-colorbond.html', RedirectView.as_view(url='/products/fascia-internal-cover-caps-colorbond')),
    path('fascia-accessories/69-fascia-internal-cover-caps-colorbond.html', RedirectView.as_view(url='/products/fascia-internal-cover-caps-colorbond')),
    path('fascia-accessories/69-fascia-internal-cover-caps-colorbond.html', RedirectView.as_view(url='/products/fascia-internal-cover-caps-colorbond')),
    path('victoria/22-colorbond-mini-orb-corrugated-roofing-sheets.html', RedirectView.as_view(url='/products/colorbond-mini-orb-corrugated-roofing-sheets')),
    path('victoria/21-mini-orb-zincalume-roofing-sheets.html', RedirectView.as_view(url='/products/mini-orb-zincalume-roofing-sheets')),
    path('roofing-tools/45-turn-up-down-tool-trimdek-or-similar-roofing.html', RedirectView.as_view(url='/products/turn-up-down-tool-trimdek-or-similar-roofing')),
    path('roofing-tools/45-turn-up-down-tool-trimdek-or-similar-roofing.html', RedirectView.as_view(url='/products/turn-up-down-tool-trimdek-or-similar-roofing')),
    path('roofing-tools/45-turn-up-down-tool-trimdek-or-similar-roofing.html', RedirectView.as_view(url='/products/turn-up-down-tool-trimdek-or-similar-roofing')),
    path('ridge/80-zincalume-roll-top-ridge-capping.html', RedirectView.as_view(url='/products/zincalume-roll-top-ridge-capping')),
    path('ridge/473-colorbond-roll-top-capping-queensland.html', RedirectView.as_view(url='/products/colorbond-roll-top-capping-queensland')),
    path('ridge/472-colorbond-roll-top-capping-new-south-wales.html', RedirectView.as_view(url='/products/colorbond-roll-top-capping-new-south-wales')),
    path('ridge/474-zincalume-roll-top-ridge-capping.html', RedirectView.as_view(url='/products/zincalume-roll-top-ridge-capping-new-south-wales')),
    path('ridge/475-zincalume-roll-top-capping-40-bmt-queensland.html', RedirectView.as_view(url='/products/zincalume-roll-top-capping-40-bmt-queensland')),
    path('gutter-guard/114-gutter-guard-leafless-colorbond.html', RedirectView.as_view(url='/products/gutter-guard-leafless-colorbond')),
    path('gutter-guard/114-gutter-guard-leafless-colorbond.html', RedirectView.as_view(url='/products/gutter-guard-leafless-colorbond')),
    path('gutter-guard/114-gutter-guard-leafless-colorbond.html', RedirectView.as_view(url='/products/gutter-guard-leafless-colorbond')),
    path('foam-strips/47-fire-resistant-foam-joint-filler-.html', RedirectView.as_view(url='/products/fire-resistant-foam-joint-filler-')),
    path('foam-strips/47-fire-resistant-foam-joint-filler-.html', RedirectView.as_view(url='/products/fire-resistant-foam-joint-filler-')),
    path('foam-strips/47-fire-resistant-foam-joint-filler-.html', RedirectView.as_view(url='/products/fire-resistant-foam-joint-filler-')),
    path('roofing-tools/46-turn-up-down-tool-klip-lok-roofing-sheets-or-similar-.html', RedirectView.as_view(url='/products/turn-up-down-tool-klip-lok-roofing')),
    path('roofing-tools/46-turn-up-down-tool-klip-lok-roofing-sheets-or-similar-.html', RedirectView.as_view(url='/products/turn-up-down-tool-klip-lok-roofing')),
    path('roofing-tools/46-turn-up-down-tool-klip-lok-roofing-sheets-or-similar-.html', RedirectView.as_view(url='/products/turn-up-down-tool-klip-lok-roofing')),
    path('flashings/400-colorbond-right-angle-flashing-100-x-100.html', RedirectView.as_view(url='/products/colorbond-right-angle-flashing-100-x-100')),
    path('flashings/400-colorbond-right-angle-flashing-100-x-100.html', RedirectView.as_view(url='/products/colorbond-right-angle-flashing-100-x-100')),
    path('flashings/400-colorbond-right-angle-flashing-100-x-100.html', RedirectView.as_view(url='/products/colorbond-right-angle-flashing-100-x-100')),
    path('insulation/75-foil-roof-sisalation.html', RedirectView.as_view(url='/products/foil-roof-sisalation')),
    path('insulation/75-foil-roof-sisalation.html', RedirectView.as_view(url='/products/foil-roof-sisalation')),
    path('insulation/75-foil-roof-sisalation.html', RedirectView.as_view(url='/products/foil-roof-sisalation')),
    path('insulation/76-55mm-roofing-insulation-blanket-foil.html', RedirectView.as_view(url='/products/55mm-roofing-insulation-blanket-foil')),
    path('insulation/76-55mm-roofing-insulation-blanket-foil.html', RedirectView.as_view(url='/products/55mm-roofing-insulation-blanket-foil')),
    path('insulation/76-55mm-roofing-insulation-blanket-foil.html', RedirectView.as_view(url='/products/55mm-roofing-insulation-blanket-foil')),
    path('insulation/77-75mm-roofing-blanket-foil-.html', RedirectView.as_view(url='/products/75mm-roofing-blanket-foil-')),
    path('insulation/77-75mm-roofing-blanket-foil-.html', RedirectView.as_view(url='/products/75mm-roofing-blanket-foil-')),
    path('insulation/77-75mm-roofing-blanket-foil-.html', RedirectView.as_view(url='/products/75mm-roofing-blanket-foil-')),
    path('valley/82-colorbond-valley-gutter-flashing.html', RedirectView.as_view(url='/products/colorbond-valley-gutter-flashing')),
    path('downpipe-accessories/297-stand-off-bracket.html', RedirectView.as_view(url='/products/stand-off-bracket')),
    path('downpipe-accessories/297-stand-off-bracket.html', RedirectView.as_view(url='/products/stand-off-bracket')),
    path('downpipe-accessories/297-stand-off-bracket.html', RedirectView.as_view(url='/products/stand-off-bracket')),
    path('apron/87-colorbond-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-roof-flashing')),
    path('apron/87-colorbond-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-roof-flashing')),
    path('apron/87-colorbond-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-roof-flashing')),
    path('apron/161-colorbond-apron-flashing-suit-trimdek-sheet-profile.html', RedirectView.as_view(url='/products/colorbond-apron-flashing-suit-trimdek-sheet')),
    path('apron/161-colorbond-apron-flashing-suit-trimdek-sheet-profile.html', RedirectView.as_view(url='/products/colorbond-apron-flashing-suit-trimdek-sheet')),
    path('apron/161-colorbond-apron-flashing-suit-trimdek-sheet-profile.html', RedirectView.as_view(url='/products/colorbond-apron-flashing-suit-trimdek-sheet')),
    path('barge-capping/162-colorbond-corner-flashing.html', RedirectView.as_view(url='/products/colorbond-corner-flashing')),
    path('barge-capping/162-colorbond-corner-flashing.html', RedirectView.as_view(url='/products/colorbond-corner-flashing')),
    path('barge-capping/162-colorbond-corner-flashing.html', RedirectView.as_view(url='/products/colorbond-corner-flashing')),
    path('accessories/48-silicone-clear-or-grey-roof-and-gutter.html', RedirectView.as_view(url='/products/silicone-clear-or-grey-roof-and-gutter')),
    path('accessories/48-silicone-clear-or-grey-roof-and-gutter.html', RedirectView.as_view(url='/products/silicone-clear-or-grey-roof-and-gutter')),
    path('accessories/48-silicone-clear-or-grey-roof-and-gutter.html', RedirectView.as_view(url='/products/silicone-clear-or-grey-roof-and-gutter')),
    path('barge-capping/164-colorbond-corner-capping-flashing.html', RedirectView.as_view(url='/products/colorbond-corner-capping-flashing')),
    path('barge-capping/164-colorbond-corner-capping-flashing.html', RedirectView.as_view(url='/products/colorbond-corner-capping-flashing')),
    path('barge-capping/164-colorbond-corner-capping-flashing.html', RedirectView.as_view(url='/products/colorbond-corner-capping-flashing')),
    path('flashings/385-colorbond-box-gutter-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-box-gutter-roof-flashing')),
    path('flashings/385-colorbond-box-gutter-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-box-gutter-roof-flashing')),
    path('flashings/385-colorbond-box-gutter-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-box-gutter-roof-flashing')),
    path('flashings/94-colorbond-box-gutter-roof-flashing-200.html', RedirectView.as_view(url='/products/colorbond-box-gutter-roof-flashing-200')),
    path('flashings/94-colorbond-box-gutter-roof-flashing-200.html', RedirectView.as_view(url='/products/colorbond-box-gutter-roof-flashing-200')),
    path('flashings/94-colorbond-box-gutter-roof-flashing-200.html', RedirectView.as_view(url='/products/colorbond-box-gutter-roof-flashing-200')),
    path('ridge/158-colorbond-roof-flashing-corrugated.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-corrugated')),
    path('ridge/158-colorbond-roof-flashing-corrugated.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-corrugated')),
    path('ridge/158-colorbond-roof-flashing-corrugated.html', RedirectView.as_view(url='/products/colorbond-roof-flashing-corrugated')),
    path('ridge/90-colorbond-flat-roof-flashing-suit-trimdek-roof.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-suit-trimdek-roof')),
    path('ridge/90-colorbond-flat-roof-flashing-suit-trimdek-roof.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-suit-trimdek-roof')),
    path('ridge/90-colorbond-flat-roof-flashing-suit-trimdek-roof.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-suit-trimdek-roof')),
    path('home/391-colorbond-flat-sheet-600mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-600mm-wide-')),
    path('home/391-colorbond-flat-sheet-600mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-600mm-wide-')),
    path('home/391-colorbond-flat-sheet-600mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-600mm-wide-')),
    path('home/391-colorbond-flat-sheet-600mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-750mm-wide-')),
    path('home/391-colorbond-flat-sheet-600mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-750mm-wide-')),
    path('home/391-colorbond-flat-sheet-600mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-750mm-wide-')),
    path('flashings/387-colorbond-flat-sheet-300mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-300mm')),
    path('flashings/387-colorbond-flat-sheet-300mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-300mm')),
    path('flashings/387-colorbond-flat-sheet-300mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-300mm')),
    path('home/389-colorbond-flat-sheet-450mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-450mm-wide-')),
    path('home/389-colorbond-flat-sheet-450mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-450mm-wide-')),
    path('home/389-colorbond-flat-sheet-450mm-wide-.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-450mm-wide-')),
    path('barge-capping/96-colorbond-parapet-capping-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-parapet-capping-roof-flashing')),
    path('barge-capping/96-colorbond-parapet-capping-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-parapet-capping-roof-flashing')),
    path('barge-capping/96-colorbond-parapet-capping-roof-flashing.html', RedirectView.as_view(url='/products/colorbond-parapet-capping-roof-flashing')),
    path('barge-capping/550-colorbond-parapet-capping-150mm.html', RedirectView.as_view(url='/products/colorbond-parapet-capping-150mm')),
    path('barge-capping/550-colorbond-parapet-capping-150mm.html', RedirectView.as_view(url='/products/colorbond-parapet-capping-150mm')),
    path('barge-capping/550-colorbond-parapet-capping-150mm.html', RedirectView.as_view(url='/products/colorbond-parapet-capping-150mm')),
    path('window-flashings/406-colorbond-z-window-flashing-50.html', RedirectView.as_view(url='/products/colorbond-z-window-flashing-50')),
    path('window-flashings/406-colorbond-z-window-flashing-50.html', RedirectView.as_view(url='/products/colorbond-z-window-flashing-50')),
    path('window-flashings/406-colorbond-z-window-flashing-50.html', RedirectView.as_view(url='/products/colorbond-z-window-flashing-50')),
    path('insulation/499-vapawrap-permeable-wall.html', RedirectView.as_view(url='/products/vapawrap-permeable-wall')),
    path('window-flashings/503-colorbond-z-window-flashing-100mm.html', RedirectView.as_view(url='/products/colorbond-z-window-flashing-100mm')),
    path('window-flashings/503-colorbond-z-window-flashing-100mm.html', RedirectView.as_view(url='/products/colorbond-z-window-flashing-100mm')),
    path('window-flashings/503-colorbond-z-window-flashing-100mm.html', RedirectView.as_view(url='/products/colorbond-z-window-flashing-100mm')),
    path('downpipe-accessories/298-adjustable-stand-off-bracket.html', RedirectView.as_view(url='/products/adjustable-stand-off-bracket')),
    path('downpipe-accessories/298-adjustable-stand-off-bracket.html', RedirectView.as_view(url='/products/adjustable-stand-off-bracket')),
    path('downpipe-accessories/298-adjustable-stand-off-bracket.html', RedirectView.as_view(url='/products/adjustable-stand-off-bracket')),
    path('insulation/500-vapawrap-permeable-roof.html', RedirectView.as_view(url='/products/vapawrap-permeable-roof')),
    path('insulation/39-spotfix-foil-fasteners-fasten-insulation-into-timber-battens-.html', RedirectView.as_view(url='/products/spotfix-foil-fasteners')),
    path('insulation/39-spotfix-foil-fasteners-fasten-insulation-into-timber-battens-.html', RedirectView.as_view(url='/products/spotfix-foil-fasteners')),
    path('insulation/39-spotfix-foil-fasteners-fasten-insulation-into-timber-battens-.html', RedirectView.as_view(url='/products/spotfix-foil-fasteners')),
    path('insulation/78-roof-safety-wire-mesh-ausmesh.html', RedirectView.as_view(url='/products/roof-safety-wire-mesh-ausmesh')),
    path('insulation/78-roof-safety-wire-mesh-ausmesh.html', RedirectView.as_view(url='/products/roof-safety-wire-mesh-ausmesh')),
    path('insulation/78-roof-safety-wire-mesh-ausmesh.html', RedirectView.as_view(url='/products/roof-safety-wire-mesh-ausmesh')),
    path('flashings/342-colorbond-flashing-klip-lok-roofing.html', RedirectView.as_view(url='/products/colorbond-flashing-klip-lok-roofing')),
    path('flashings/342-colorbond-flashing-klip-lok-roofing.html', RedirectView.as_view(url='/products/colorbond-flashing-klip-lok-roofing')),
    path('flashings/342-colorbond-flashing-klip-lok-roofing.html', RedirectView.as_view(url='/products/colorbond-flashing-klip-lok-roofing')),
    path('31-downpipe-accessories', RedirectView.as_view(url='/products/Downpipe-Pop-COLORBOND-ZINCALUME')),
    path('31-downpipe-accessories', RedirectView.as_view(url='/products/Downpipe-Pop-COLORBOND-ZINCALUME')),
    path('31-downpipe-accessories', RedirectView.as_view(url='/products/Downpipe-Pop-COLORBOND-ZINCALUME')),
    path('victoria/126-colorbond-downpipe-100-x-50.html', RedirectView.as_view(url='/products/colorbond-or-zincalume-downpipe-100-x-50')),
    path('victoria/126-colorbond-downpipe-100-x-50.html', RedirectView.as_view(url='/products/colorbond-or-zincalume-downpipe-100-x-50')),
    path('victoria/126-colorbond-downpipe-100-x-50.html', RedirectView.as_view(url='/products/colorbond-or-zincalume-downpipe-100-x-50')),
    path('act/359-colorbond-downpipe-100-x-50.html', RedirectView.as_view(url='/products/colorbond-downpipe-100-x-50-NSW')),
    path('victoria/128-colorbond-downpipe-adjustable-offset-100-x-50.html', RedirectView.as_view(url='/products/colorbond-downpipe-adjustable-offset-100-x-50')),
    path('act/361-colorbond-downpipe-adjustable-offset-100-x-50-nsw-act.html', RedirectView.as_view(url='/products/colorbond-downpipe-adjustable-offset-100-x-50')),
    path('victoria/130-colorbond-downpipe-100-x-75.html', RedirectView.as_view(url='/products/colorbond-or-zincalume-downpipe-100-x-75')),
    path('act/363--downpipe-100-x-75-colorbond-nsw-act.html', RedirectView.as_view(url='/products/-downpipe-100-x-75-colorbond-nsw')),
    path('victoria/132-colorbond-downpipe-100-x-75-adjustable-offset-.html', RedirectView.as_view(url='/products/colorbond-downpipe-100-x-75-adjustable-offset-')),
    path('victoria/176-colorbond-75mm-round-downpipe.html', RedirectView.as_view(url='/products/colorbond-75mm-round-downpipe')),
    path('victoria/374-colorbond-downpipe-round-75mm-adjustable-offset.html', RedirectView.as_view(url='/products/colorbond-downpipe-round-75mm-adjustable-offset')),
    path('victoria/134-colorbond-downpipe-90mm-round-.html', RedirectView.as_view(url='/products/colorbond-downpipe-90mm-round-')),
    path('queensland/271-downpipe-90mm-round-colorbond-brisbane-.html', RedirectView.as_view(url='/products/colorbond-downpipe-90mm-round-')),
    path('ridge/281-colorbond-flat-roof-flashing-140mm.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-140mm')),
    path('ridge/281-colorbond-flat-roof-flashing-140mm.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-140mm')),
    path('ridge/281-colorbond-flat-roof-flashing-140mm.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-140mm')),
    path('valley/469-colorbond-gutter-flashing-queensland.html', RedirectView.as_view(url='/products/colorbond-gutter-flashing-queensland')),
    path('valley/468-colorbond-gutter-flashing-new-south-wales.html', RedirectView.as_view(url='/products/colorbond-gutter-flashing-new-south-wales')),
    path('apron/478-colorbond-flashing-150mm.html', RedirectView.as_view(url='/products/colorbond-flashing-150mm')),
    path('apron/478-colorbond-flashing-150mm.html', RedirectView.as_view(url='/products/colorbond-flashing-150mm')),
    path('apron/478-colorbond-flashing-150mm.html', RedirectView.as_view(url='/products/colorbond-flashing-150mm')),
    path('flashings/502-colorbond-flat-sheet-900mm.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-900mm')),
    path('flashings/502-colorbond-flat-sheet-900mm.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-900mm')),
    path('flashings/502-colorbond-flat-sheet-900mm.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-900mm')),
    path('flashings/333-colorbond-ridge-capping-to-suit-trimdek.html', RedirectView.as_view(url='/products/colorbond-ridge-capping-to-suit-trimdek')),
    path('flashings/333-colorbond-ridge-capping-to-suit-trimdek.html', RedirectView.as_view(url='/products/colorbond-ridge-capping-to-suit-trimdek')),
    path('flashings/333-colorbond-ridge-capping-to-suit-trimdek.html', RedirectView.as_view(url='/products/colorbond-ridge-capping-to-suit-trimdek')),
    path('ridge/518-colorbond-flat-roof-flashing-klip-lok.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-klip-lok')),
    path('ridge/518-colorbond-flat-roof-flashing-klip-lok.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-klip-lok')),
    path('ridge/518-colorbond-flat-roof-flashing-klip-lok.html', RedirectView.as_view(url='/products/colorbond-flat-roof-flashing-klip-lok')),
    path('ridge/520-colorbond-flat-roof-flashing-klip-lok-260mm.html', RedirectView.as_view(url='/products/260mm-flat-ridge-roof-flashing-suit-klip-lok-colorbond-or-zincalume')),
    path('ridge/520-colorbond-flat-roof-flashing-klip-lok-260mm.html', RedirectView.as_view(url='/products/260mm-flat-ridge-roof-flashing-suit-klip-lok-colorbond-or-zincalume')),
    path('ridge/520-colorbond-flat-roof-flashing-klip-lok-260mm.html', RedirectView.as_view(url='/products/260mm-flat-ridge-roof-flashing-suit-klip-lok-colorbond-or-zincalume')),
    path('home/531-colorbond-flat-sheet-1050mm-wide.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-1050mm-wide')),
    path('home/531-colorbond-flat-sheet-1050mm-wide.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-1050mm-wide')),
    path('home/531-colorbond-flat-sheet-1050mm-wide.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-1050mm-wide')),
    path('home/534-colorbond-flat-sheet-1200mm-wide.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-1200mm-wide')),
    path('home/534-colorbond-flat-sheet-1200mm-wide.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-1200mm-wide')),
    path('home/534-colorbond-flat-sheet-1200mm-wide.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-1200mm-wide')),
    path('flashings/535-colorbond-flat-sheet-150mm.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-150mm')),
    path('flashings/535-colorbond-flat-sheet-150mm.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-150mm')),
    path('flashings/535-colorbond-flat-sheet-150mm.html', RedirectView.as_view(url='/products/colorbond-flat-sheet-150mm')),
    path('valley/539-colorbond-gutter-flashing-190mm.html', RedirectView.as_view(url='/products/colorbond-gutter-flashing-190mm')),
    path('barge-capping/92-barge-roll-capping-colorbond-.html', RedirectView.as_view(url='/products/barge-roll-capping-colorbond-')),
    path('barge-capping/92-barge-roll-capping-colorbond-.html', RedirectView.as_view(url='/products/barge-roll-capping-colorbond-')),
    path('barge-capping/92-barge-roll-capping-colorbond-.html', RedirectView.as_view(url='/products/barge-roll-capping-colorbond-')),
    path('apron/526-150mm-colorbond-flashing-trimdek.html', RedirectView.as_view(url='/products/150mm-colorbond-flashing-trimdek')),
    path('apron/526-150mm-colorbond-flashing-trimdek.html', RedirectView.as_view(url='/products/150mm-colorbond-flashing-trimdek')),
    path('apron/526-150mm-colorbond-flashing-trimdek.html', RedirectView.as_view(url='/products/150mm-colorbond-flashing-trimdek')),
    path('flashings/541-colorbond-apron-flashing-klip-lok.html', RedirectView.as_view(url='/products/colorbond-apron-flashing-klip-lok')),
    path('flashings/541-colorbond-apron-flashing-klip-lok.html', RedirectView.as_view(url='/products/colorbond-apron-flashing-klip-lok')),
    path('flashings/541-colorbond-apron-flashing-klip-lok.html', RedirectView.as_view(url='/products/colorbond-apron-flashing-klip-lok')),
    path('window-flashings/513-colorbond-window-flashing-40mm.html', RedirectView.as_view(url='/products/colorbond-window-flashing-40mm')),
    path('window-flashings/513-colorbond-window-flashing-40mm.html', RedirectView.as_view(url='/products/colorbond-window-flashing-40mm')),
    path('window-flashings/513-colorbond-window-flashing-40mm.html', RedirectView.as_view(url='/products/colorbond-window-flashing-40mm')),
    path('window-flashings/538-colorbond-flashing-150.html', RedirectView.as_view(url='/products/colorbond-z-flashing-150')),
    path('window-flashings/538-colorbond-flashing-150.html', RedirectView.as_view(url='/products/colorbond-z-flashing-150')),
    path('window-flashings/538-colorbond-flashing-150.html', RedirectView.as_view(url='/products/colorbond-z-flashing-150')),
    path('window-flashings/407-sign-white-z-flashing.html', RedirectView.as_view(url='/products/sign-white-z-flashing')),
    path('victoria/104-guttering-colorbond-quad.html', RedirectView.as_view(url='/products/guttering-colorbond-quad')),
    path('victoria/105-guttering-zincalume-quad.html', RedirectView.as_view(url='/products/guttering-zincalume-quad')),
    path('victoria/59-internal-guttering-quad-clips.html', RedirectView.as_view(url='/products/internal-guttering-quad-clips')),
    path('victoria/61-colorbond-guttering-cast-angles-quad.html', RedirectView.as_view(url='/products/colorbond-guttering-cast-angles-quad')),
    path('victoria/57-colorbond-guttering-external-clip.html', RedirectView.as_view(url='/products/colorbond-guttering-external-clip')),
    path('victoria/60-guttering-quad-cast-angle-zincalume.html', RedirectView.as_view(url='/products/guttering-quad-cast-angle-zincalume-internal')),
    path('victoria/58-zincalume-guttering-external-clips-quad-.html', RedirectView.as_view(url='/products/zincalume-guttering-external-clips-quad')),
    path('victoria/63-guttering-stopends-zincalume-quad-.html', RedirectView.as_view(url='/products/guttering-stopends-zincalume-quad-')),
    path('victoria/62-guttering-stopends-colorbond-quad-.html', RedirectView.as_view(url='/products/guttering-stopends-colorbond-quad-')),
    path('victoria/119-guttering-colorbond-sheerline.html', RedirectView.as_view(url='/products/guttering-colorbond-sheerline')),
    path('victoria/120-guttering-zincalume-sheerline.html', RedirectView.as_view(url='/products/guttering-zincalume-sheerline')),
    path('victoria/232-guttering-stopends-colorbond-sheerline.html', RedirectView.as_view(url='/products/guttering-stopends-colorbond-sheerline')),
    path('victoria/231-guttering-internal-clips-zincalume-sheerline.html', RedirectView.as_view(url='/products/guttering-internal-clips-zincalume-sheerline')),
    path('victoria/233-zincalume-guttering-stopends-sheerline.html', RedirectView.as_view(url='/products/zincalume-guttering-stopends-sheerline')),
    path('victoria/117-guttering-colorbond-trimline.html', RedirectView.as_view(url='/products/guttering-colorbond-trimline')),
    path('victoria/105-guttering-zincalume-quad.html', RedirectView.as_view(url='/products/guttering-zincalume-trimline')),
    path('victoria/227-guttering-internal-clips-zincalume-trimline-.html', RedirectView.as_view(url='/products/guttering-internal-clips-zincalume-trimline-')),
    path('victoria/228-guttering-stopends-colorbond-trimline.html', RedirectView.as_view(url='/products/guttering-stopends-colorbond-trimline')),
    path('victoria/230-guttering-stopends-zincalume-trimline-.html', RedirectView.as_view(url='/products/guttering-stopends-zincalume-trimline-')),
    path('new-south-wales/106-colorbond-guttering-quad-115mm-hi-front.html', RedirectView.as_view(url='/products/colorbond-guttering-quad-115mm-hi-front')),
    path('new-south-wales/107-guttering-zincalume-quad-115mm-hi-front.html', RedirectView.as_view(url='/products/guttering-zincalume-quad-115mm-hi-front')),
    path('new-south-wales/234-guttering-internal-clips-zincalume-.html', RedirectView.as_view(url='/products/guttering-internal-clips-zincalume-')),
    path('new-south-wales/236-guttering-external-clips-colorbond-quad.html', RedirectView.as_view(url='/products/guttering-external-clips-colorbond-quad')),
    path('new-south-wales/238-guttering-cast-angle-zincalume-quad.html', RedirectView.as_view(url='/products/guttering-cast-angle-zincalume-quad')),
    path('new-south-wales/371-guttering-external-clips-zincalume.html', RedirectView.as_view(url='/products/guttering-external-clips-zincalume')),
    path('new-south-wales/239-guttering-stopends-zincalume-quad-.html', RedirectView.as_view(url='/products/guttering-stopends-zincalume-quad-nsw')),
    path('new-south-wales/370-guttering-cast-angles-colorbond-quad.html', RedirectView.as_view(url='/products/guttering-cast-angles-colorbond-quad')),
    path('new-south-wales/451-guttering-colorbond-sheerline.html', RedirectView.as_view(url='/products/guttering-colorbond-sheerline-nsw')),
    path('new-south-wales/240-guttering-stopends-colorbond-quad-.html', RedirectView.as_view(url='/products/guttering-stopends-colorbond-quad-nsw')),
    path('queensland/110-guttering-colorbond-quad-low-front.html', RedirectView.as_view(url='/products/guttering-colorbond-quad-low-front')),
    path('queensland/241-zincalume-hi-front-quad-internal-clips-brisbane.html', RedirectView.as_view(url='/products/zincalume-hi-front-quad-internal-clips-brisbane')),
    path('queensland/111-guttering-zincalume-quad-150mm-low-front.html', RedirectView.as_view(url='/products/guttering-zincalume-quad-150mm-low-front')),
    path('queensland/243-guttering-stopends-zincalume-quad-queensland-.html', RedirectView.as_view(url='/products/guttering-stopends-zincalume-quad-queensland-')),
    path('queensland/244-guttering-stopends-colorbond-quad-queensland.html', RedirectView.as_view(url='/products/guttering-stopends-colorbond-quad-queensland')),
    path('queensland/245-manufactured-quad-guttering-corners-zincalume.html', RedirectView.as_view(url='/products/manufactured-quad-guttering-corners-zincalume')),
    path('queensland/246-manufactured-quad-guttering-corners-colorbond.html', RedirectView.as_view(url='/products/manufactured-quad-guttering-corners-colorbond')),
    path('queensland/315-zincalume-low-front-quad-gutter-internal-clips.html', RedirectView.as_view(url='/products/zincalume-low-front-quad-gutter-internal-clips')),
    path('queensland/66-spike-clip-to-suit-low-front-quad-guttering-zincalume-.html', RedirectView.as_view(url='/products/spike-clip-to-suit-low-front-quad-guttering-zincalume-')),
    path('queensland/64-spike-clip-to-suit-hi-front-quad-guttering.html', RedirectView.as_view(url='/products/spike-clip-to-suit-hi-front-quad-guttering')),
    path('queensland/65-spike-clip-to-suit-low-front-quad-guttering-colorbond-.html', RedirectView.as_view(url='/products/spike-clip-to-suit-low-front-quad-guttering-colorbond-')),
    path('queensland/109-guttering-zincalume-quad-hi-front.html', RedirectView.as_view(url='/products/guttering-zincalume-quad-hi-front')),
    path('flashings/545-colorbond-box-gutter-300.html', RedirectView.as_view(url='/products/colorbond-box-gutter-300')),
    path('flashings/545-colorbond-box-gutter-300.html', RedirectView.as_view(url='/products/colorbond-box-gutter-300')),
    path('flashings/545-colorbond-box-gutter-300.html', RedirectView.as_view(url='/products/colorbond-box-gutter-300')),
    path('flashings/548-colorbond-box-gutter-400.html', RedirectView.as_view(url='/products/colorbond-box-gutter-400')),
    path('flashings/548-colorbond-box-gutter-400.html', RedirectView.as_view(url='/products/colorbond-box-gutter-400')),
    path('flashings/548-colorbond-box-gutter-400.html', RedirectView.as_view(url='/products/colorbond-box-gutter-400')),
    path('new-south-wales/452-guttering-internal-clips-zincalume-sheerline.html', RedirectView.as_view(url='/products/guttering-internal-clips-zincalume-sheerline-nsw')),
    path('new-south-wales/453-guttering-stopends-colorbond-sheerline.html', RedirectView.as_view(url='/products/guttering-stopends-colorbond-sheerline-nsw')),
    path('new-south-wales/454-guttering-internal-clips-zincalume-sheerline.html', RedirectView.as_view(url='/products/guttering-universal-clips-zincalume-sheerline')),
    path('new-south-wales/483-colorbond-gutter-stopends-trimline.html', RedirectView.as_view(url='/products/colorbond-gutter-stopends-trimline')),
    path('new-south-wales/482-zincalume-gutter-internal-clips-trimline.html', RedirectView.as_view(url='/products/zincalume-gutter-internal-clips-trimline')),
    path('new-south-wales/476-zincalume-gutter-sheerline.html', RedirectView.as_view(url='/products/zincalume-gutter-sheerline')),
    path('new-south-wales/481-colorbond-gutter-trimline.html', RedirectView.as_view(url='/products/colorbond-gutter-trimline')),
    path('new-south-wales/477-guttering-stopends-zincalume-sheerline.html', RedirectView.as_view(url='/products/guttering-stopends-zincalume-sheerline')),
    path('queensland/108-guttering-colorbond-quad.html', RedirectView.as_view(url='/products/guttering-colorbond-quad-150')),
    path('queensland/455-guttering-colorbond-trimline.html', RedirectView.as_view(url='/products/guttering-colorbond-trimline-qld')),
    path('queensland/456-guttering-zincalume-trimline.html', RedirectView.as_view(url='/products/guttering-zincalume-trimline-qld')),
    path('queensland/457-guttering-internal-clips-zincalume-trimline.html', RedirectView.as_view(url='/products/guttering-internal-clips-zincalume-trimline-qld')),
    path('queensland/458-guttering-stopends-colorbond-trimline.html', RedirectView.as_view(url='/products/guttering-stopends-colorbond-trimline-qld')),
    path('queensland/459-guttering-stopends-zincalume-trimline.html', RedirectView.as_view(url='/products/guttering-stopends-zincalume-trimline-qld')),
    path('new-south-wales/484-guttering-zincalume-trimline.html', RedirectView.as_view(url='/products/guttering-zincalume-trimline-nsw')),
    path('new-south-wales/485-guttering-stopends-zincalume-sheerline-new-south-wales.html', RedirectView.as_view(url='/products/guttering-stopends-zincalume-sheerline-new-south-wales')),
    path('new-south-wales/491-colorbond-gutter-half-round.html', RedirectView.as_view(url='/products/colorbond-gutter-half-round')),
    path('new-south-wales/492-colorbond-half-round-gutter-stop-ends.html', RedirectView.as_view(url='/products/colorbond-half-round-gutter-stop-ends')),
    path('new-south-wales/493-colorbond-half-round-gutter-corner.html', RedirectView.as_view(url='/products/colorbond-half-round-gutter-corner')),
    path('new-south-wales/494-colorbond-half-round-gutter-clip.html', RedirectView.as_view(url='/products/colorbond-half-round-gutter-clip')),
    path('queensland/505-colorbond-half-round-gutter.html', RedirectView.as_view(url='/products/colorbond-half-round-gutter-qld')),
    path('queensland/506-colorbond-half-round-gutter-stop-end.html', RedirectView.as_view(url='/products/colorbond-half-round-gutter-stop-end')),
    path('queensland/507-colorbond-half-round-gutter-corner.html', RedirectView.as_view(url='/products/colorbond-half-round-gutter-corner-qld')),
    path('queensland/508-colorbond-half-round-gutter-external-clip.html', RedirectView.as_view(url='/products/colorbond-half-round-gutter-external-clip')),
    path('queensland/509-zincalume-half-round-gutter.html', RedirectView.as_view(url='/products/zincalume-half-round-gutter')),
    path('victoria/345-colorbond-downpipe-round-offset.html', RedirectView.as_view(url='/products/colorbond-downpipe-round-offset')),
    path('new-south-wales/487-colorbond-downpipe-90mm-round.html', RedirectView.as_view(url='/products/colorbond-downpipe-90mm-round-nsw')),
    path('queensland/510-zincalume-half-round-gutter-stop-end.html', RedirectView.as_view(url='/products/zincalume-half-round-gutter-stop-end')),
    path('queensland/507-colorbond-half-round-gutter-corner.html', RedirectView.as_view(url='/products/zincalume-half-round-gutter-cast-corner')),
    path('queensland/512-zincalume-half-round-gutter-external-clip.html', RedirectView.as_view(url='/products/zincalume-half-round-gutter-external-clip')),
    path('new-south-wales/522-zincalume-half-round-gutter.html', RedirectView.as_view(url='/products/zincalume-half-round-gutter-nsw')),
    path('new-south-wales/523-zincalume-half-round-gutter-stop-end.html', RedirectView.as_view(url='/products/zincalume-half-round-gutter-stop-end-nsw')),
    path('new-south-wales/524-zincalume-half-round-gutter-clip.html', RedirectView.as_view(url='/products/zincalume-half-round-gutter-clip')),
    path('new-south-wales/525-zincalume-half-round-gutter-cast-corner.html', RedirectView.as_view(url='/products/zincalume-half-round-gutter-cast-corner-nsw')),
    path('fascia-accessories/67-fascia-mitres-colorbond-external-corner.html', RedirectView.as_view(url='/products/fascia-mitres-colorbond-external-corner')),
    path('fascia-accessories/67-fascia-mitres-colorbond-external-corner.html', RedirectView.as_view(url='/products/fascia-mitres-colorbond-external-corner')),
    path('fascia-accessories/67-fascia-mitres-colorbond-external-corner.html', RedirectView.as_view(url='/products/fascia-mitres-colorbond-external-corner')),
    path('victoria/270-colorbond-fascia-cover.html', RedirectView.as_view(url='/products/colorbond-fascia-cover')),
    path('victoria/167-zincalume-fascia-cover.html', RedirectView.as_view(url='/products/zincalume-fascia-cover')),
    path('new-south-wales/268-colorbond-fascia-cover.html', RedirectView.as_view(url='/products/colorbond-fascia-cover-nsw')),
    path('new-south-wales/269-zincalume-fascia-cover.html', RedirectView.as_view(url='/products/zincalume-fascia-cover-nsw')),
    path('accessories/40-nylon-anchors-65-x-40-box-of-100.html', RedirectView.as_view(url='/products/nylon-anchors-65-x-40-box-of-100')),
    path('accessories/40-nylon-anchors-65-x-40-box-of-100.html', RedirectView.as_view(url='/products/nylon-anchors-65-x-40-box-of-100')),
    path('accessories/40-nylon-anchors-65-x-40-box-of-100.html', RedirectView.as_view(url='/products/nylon-anchors-65-x-40-box-of-100')),
    path('fascia-accessories/461-fascia-over-strap-suit-150mm-hi-front-or-low-front-quad.htm', RedirectView.as_view(url='/products/fascia-over-strap-suit-150mm-hi-front-or-low-front-quad')),
    path('fascia-accessories/462-fascia-over-strap-suit-trimline-gutter.html', RedirectView.as_view(url='/products/fascia-over-strap-suit-trimline-gutter')),
    path('victoria/168-colorbond-roofing-spandek.html', RedirectView.as_view(url='/products/colorbond-roofing-spandek')),
    path('victoria/169-spandek-zincalume-roofing-sheets.html', RedirectView.as_view(url='/products/spandek-zincalume-roofing-sheets')),
    path('victoria/218-corrugated-iron-galvanised-roofing-sheets.html', RedirectView.as_view(url='/products/corrugated-iron-galvanised-roofing-sheets')),
    path('victoria/171-multiclad-zincalume-wall-sheets.html', RedirectView.as_view(url='/products/multiclad-zincalume-wall-sheets')),
    path('victoria/170-colorbond-multiclad-wall-sheets.html', RedirectView.as_view(url='/products/colorbond-multiclad-wall-sheets')),
    path('new-south-wales/199-colorbond-roofing-corrugated-iron-sydney.html', RedirectView.as_view(url='/products/colorbond-roofing-corrugated-iron-sydney')),
    path('new-south-wales/399-48-bmt-colorbond-roofing-corrugated-iron.html', RedirectView.as_view(url='/products/48-bmt-colorbond-roofing-corrugated-iron')),
    path('new-south-wales/25-zincalume-roofing-corrugated-iron-sheets.html', RedirectView.as_view(url='/products/zincalume-roofing-corrugated-iron-sheets')),
    path('new-south-wales/420-48-bmt-zincalume-roofing-corrugated-iron.html', RedirectView.as_view(url='/products/48-bmt-zincalume-roofing-corrugated-iron')),
    path('new-south-wales/14-colorbond-roofing-trimdek.html', RedirectView.as_view(url='/products/colorbond-roofing-trimdek')),
    path('new-south-wales/440-48-bmt-colorbond-roofing-trimdek.html', RedirectView.as_view(url='/products/48-bmt-colorbond-roofing-trimdek')),
    path('new-south-wales/27-zincalume-roofing-trimdek.html', RedirectView.as_view(url='/products/zincalume-roofing-trimdek')),
    path('new-south-wales/448-48-bmt-zincalume-roofing-trimdek.html', RedirectView.as_view(url='/products/48-bmt-zincalume-roofing-trimdek')),
    path('new-south-wales/142-colorbond-klip-lok-700.html', RedirectView.as_view(url='/products/colorbond-klip-lok-700')),
    path('new-south-wales/143-zincalume-klip-lok-700.html', RedirectView.as_view(url='/products/zincalume-klip-lok-700')),
    path('new-south-wales/433-48-bmt-zincalume-klip-lok.html', RedirectView.as_view(url='/products/48-bmt-zincalume-klip-lok')),
    path('new-south-wales/436-48-bmt-colorbond-klip-lok-700.html', RedirectView.as_view(url='/products/48-bmt-colorbond-klip-lok-700')),
    path('new-south-wales/495-colorbond-multiclad-wall-sheets.html', RedirectView.as_view(url='/products/colorbond-multiclad-wall-sheets-nsw')),
    path('new-south-wales/463-mini-orb-colorbond-corrugated-sheets.html', RedirectView.as_view(url='/products/mini-orb-colorbond-corrugated-sheets')),
    path('new-south-wales/464-mini-orb-zincalume.html', RedirectView.as_view(url='/products/mini-orb-zincalume')),
    path('new-south-wales/516-corrugated-iron-galvanised-roofing.html', RedirectView.as_view(url='/products/corrugated-iron-galvanised-roofing')),
    path('queensland/248-colorbond-downpipe-100-x-75.html', RedirectView.as_view(url='/products/-downpipe-100-x-75-colorbond-QLD')),
    path('new-south-wales/489-colorbond-spandek-roofing-sheets.html', RedirectView.as_view(url='/products/colorbond-spandek-roofing-sheets')),
    path('new-south-wales/498-zincalume-spandek-.html', RedirectView.as_view(url='/products/zincalume-spandek-')),
    path('queensland/12-colorbond-roofing-corrugated-iron.html', RedirectView.as_view(url='/products/colorbond-roofing-corrugated-iron')),
    path('queensland/35-zincalume-corrugated-iron-roof.html', RedirectView.as_view(url='/products/zincalume-corrugated-iron-roof')),
    path('queensland/395-48-colorbond-corrugated-iron.html', RedirectView.as_view(url='/products/48-colorbond-corrugated-iron')),
    path('queensland/396-zincalume-corrugated-iron-roofing-48.html', RedirectView.as_view(url='/products/zincalume-corrugated-iron-roofing-48')),
    path('queensland/42-colorbond-trimdek.html', RedirectView.as_view(url='/products/colorbond-trimdek')),
    path('queensland/50-zincalume-trimdek-roofing.html', RedirectView.as_view(url='/products/zincalume-trimdek-roofing')),
    path('queensland/450-48-bmt-colorbond-trimdek.html', RedirectView.as_view(url='/products/48-bmt-colorbond-trimdek')),
    path('queensland/449-48-zincalume-trimdek-roofing-sheets.html', RedirectView.as_view(url='/products/48-zincalume-trimdek-roofing-sheets')),
    path('queensland/153-colorbond-roofing-klip-lok.html', RedirectView.as_view(url='/products/colorbond-roofing-klip-lok')),
    path('queensland/152-zincalume-klip-lok-roofing.html', RedirectView.as_view(url='/products/zincalume-klip-lok-roofing')),
    path('queensland/437-48-bmt-colorbond-klip-lok.html', RedirectView.as_view(url='/products/48-bmt-colorbond-klip-lok')),
    path('queensland/435-48-bmt-zincalume-klip-lok.html', RedirectView.as_view(url='/products/48-bmt-zincalume-klip-lok-qld')),
    path('victoria/20-klip-lok-700-fixing-clips.html', RedirectView.as_view(url='/products/klip-lok-700-fixing-clips')),
    path('new-south-wales/446-klip-lok-700-fixing-clips.html', RedirectView.as_view(url='/products/klip-lok-700-fixing-clips')),
    path('queensland/157-klip-lok-clips.html', RedirectView.as_view(url='/products/klip-lok-700-fixing-clips')),
    path('queensland/544-mini-orb-zincalume-.html', RedirectView.as_view(url='/products/mini-orb-zincalume-')),
    path('queensland/81-colorbond-roofing-mini-orb.html', RedirectView.as_view(url='/products/colorbond-roofing-mini-orb')),
    path('queensland/178-colorbond-spandek-roofing.html', RedirectView.as_view(url='/products/colorbond-spandek-roofing')),
    path('queensland/460-spandek-zincalume-roofing-sheets.html', RedirectView.as_view(url='/products/spandek-zincalume-roofing-sheets-qld')),
    path('queensland/174-colorbond-multiclad.html', RedirectView.as_view(url='/products/colorbond-multiclad')),
    path('queensland/175-zincalume-multiclad.html', RedirectView.as_view(url='/products/zincalume-multiclad')),
    path('queensland/443-corrugated-iron-galvanised-roofing.html', RedirectView.as_view(url='/products/corrugated-iron-galvanised-roofing-qld')),
    path('victoria/23-metal-roof-battens-.html', RedirectView.as_view(url='/products/metal-roof-battens-')),
    path('new-south-wales/372-roof-battens-sydney.html', RedirectView.as_view(url='/products/metal-roof-battens-')),
    path('queensland/145-roof-battens.html', RedirectView.as_view(url='/products/roof-battens')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404
handler500 = error_500
