# Generated by Django 2.0.5 on 2019-09-15 10:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_bottom',
            field=tinymce.models.HTMLField(default='Coming Soon', verbose_name='description'),
            preserve_default=False,
        ),
    ]
