# Generated by Django 2.1.7 on 2021-06-18 04:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_description_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='', help_text='Description for SEO', max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(default='', help_text='Title for SEO', max_length=70),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_bottom',
            field=tinymce.models.HTMLField(verbose_name='description_bottom'),
        ),
    ]
