# Generated by Django 2.0.5 on 2021-06-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_description_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='', help_text='Description for SEO', max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(default='', help_text='Title for SEO', max_length=70),
        ),
    ]
