# Generated by Django 2.0.5 on 2018-10-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_additional_drop_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_session_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
