# Generated by Django 2.0.5 on 2019-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190211_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
