# Generated by Django 2.0.5 on 2019-04-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20190211_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
