# Generated by Django 2.1.7 on 2020-08-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cartitem_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='colour',
            new_name='product_colour',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='length',
            new_name='product_length',
        ),
    ]
