# Generated by Django 2.1.7 on 2020-08-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20200825_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='additional',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
