# Generated by Django 2.1.7 on 2020-08-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20200825_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_colour',
            new_name='colour',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='additional',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
    ]
