# Generated by Django 2.0.5 on 2021-08-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_auto_20200829_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFlashing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='img/')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
