# Generated by Django 2.0.5 on 2021-08-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_customflashing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customflashing',
            name='file',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
