# Generated by Django 2.0.5 on 2021-08-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_auto_20210823_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFlashingBelowMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
        ),
    ]
