# Generated by Django 2.0.3 on 2018-05-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingzone',
            name='zone_name',
        ),
        migrations.AddField(
            model_name='shipping',
            name='zone_name',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='address',
            field=models.CharField(default='test2', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='max_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text="Maximum distance for zone's delivery in kilometres", max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='state',
            field=models.CharField(default='test3', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='suburb',
            field=models.CharField(default='test4', max_length=120),
            preserve_default=False,
        ),
    ]
