# Generated by Django 2.0.3 on 2018-05-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20180514_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('VIC', 'Victoria'), ('NSW', 'New South Wales'), ('QLD', 'Queensland')], max_length=120)),
                ('postal_code', models.IntegerField(default=7)),
            ],
        ),
    ]
