# Generated by Django 2.0.3 on 2018-05-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20180514_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='approx_delivery',
        ),
        migrations.RemoveField(
            model_name='state',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='state',
            name='approx_delivery_date',
            field=models.IntegerField(default=0, help_text='Approximate time in days'),
        ),
    ]
