# Generated by Django 2.0.3 on 2018-05-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_auto_20180514_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='approx_delivery_date',
            new_name='approx_delivery_time',
        ),
    ]
