# Generated by Django 2.0.3 on 2018-05-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_auto_20180514_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suburb',
            name='state',
        ),
        migrations.RemoveField(
            model_name='suburb',
            name='title',
        ),
    ]
