# Generated by Django 2.0.5 on 2018-05-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_auto_20180514_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='supplier',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
    ]
