# Generated by Django 2.0.5 on 2018-09-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_state_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburb',
            name='message',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
