# Generated by Django 2.0.5 on 2018-10-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_suburb_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburb',
            name='message',
            field=models.CharField(blank=True, help_text="If post code isn't shipped to entirely", max_length=999, null=True),
        ),
    ]
