# Generated by Django 2.0.5 on 2020-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_auto_20181017_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisallowedShippingDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(choices=[('ALL', 'ALL'), ('ACT', 'ACT'), ('NSW', 'NSW'), ('NT', 'NT'), ('QLD', 'QLD'), ('TAS', 'TAS'), ('VIC', 'VIC'), ('WA', 'WA')], default='ALL', max_length=120)),
            ],
        ),
    ]
