# Generated by Django 2.0.3 on 2018-04-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image_imageoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
    ]
