# Generated by Django 2.0.3 on 2018-04-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180423_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_url_nsw',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_url_qld',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_url_vic',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='colouroption',
            name='option',
            field=models.ForeignKey(blank=True, help_text='Length in Metres', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Colour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Maximum length in metres', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Minimum length in metres', max_digits=20, null=True),
        ),
    ]
