# Generated by Django 2.0.3 on 2018-04-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180427_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='length',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Length in metres', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Maximum length in mm', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Minimum length in mm', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nsw_price_per_mm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nsw_supplier_per_mm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qld_price_per_mm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qld_supplier_per_mm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vic_price_per_mm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vic_supplier_per_mm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
    ]
