# Generated by Django 2.0.3 on 2018-04-30 23:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180427_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_info',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
