# Generated by Django 2.0.3 on 2018-05-01 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180501_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldropdownoption',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.AdditionalDropDown'),
        ),
    ]
