# Generated by Django 2.0.3 on 2018-05-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_additionaldropdownoption_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_dropdown_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
