# Generated by Django 2.0.3 on 2018-05-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_additional_dropdown_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='additional_dropdown_name',
            new_name='additional_dropdown_title',
        ),
    ]
