# Generated by Django 2.0.3 on 2018-05-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180502_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldropdown',
            name='additional_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='additionaldropdown',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
