# Generated by Django 2.0.3 on 2018-05-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180502_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldropdown',
            name='title',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
