# Generated by Django 2.0.3 on 2018-05-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_accessoryoption_zincalume_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryoption',
            name='zincalume_cost',
        ),
        migrations.AddField(
            model_name='additionaldropdown',
            name='zincalume_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
