# Generated by Django 2.0.3 on 2018-05-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180508_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaldropdown',
            old_name='zincalume_cost',
            new_name='zincalume_additional_cost',
        ),
    ]
