# Generated by Django 2.0.3 on 2018-05-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20180508_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaldropdown',
            old_name='additional_cost_vic',
            new_name='additional_cost',
        ),
        migrations.RemoveField(
            model_name='additionaldropdown',
            name='additional_cost_nsw',
        ),
        migrations.RemoveField(
            model_name='additionaldropdown',
            name='additional_cost_qld',
        ),
    ]
