# Generated by Django 2.0.3 on 2018-05-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20180508_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_shipping',
            field=models.BooleanField(default=False, help_text='For items that ship with standard and express flat rate'),
        ),
    ]
