# Generated by Django 2.0.5 on 2018-05-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_standard_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zincalume_discount_new_south_wales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='product',
            name='zincalume_discount_queensland',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='product',
            name='zincalume_discount_victoria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Title of tab (for SEO)', max_length=120),
        ),
    ]
