# Generated by Django 2.0.5 on 2018-05-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20180523_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplied',
            field=models.BooleanField(default=False, help_text='Supplied by an independant supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Displayed in the "featured" sections'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(help_text='Description for SEO', max_length=160),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(help_text='Title for SEO', max_length=70),
        ),
    ]
