# Generated by Django 2.0.5 on 2018-05-23 23:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20180524_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='more_info',
            field=tinymce.models.HTMLField(verbose_name='More Info'),
        ),
    ]
