# Generated by Django 2.0.5 on 2018-05-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20180524_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vic_title',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, help_text='Used for Victoria and in-house', max_length=120, null=True),
        ),
    ]
