# Generated by Django 2.0.5 on 2018-05-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20180524_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
