# Generated by Django 2.0.5 on 2018-05-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='DEFAULT', help_text='Used for Victoria and in-house', max_length=120, null=True),
        ),
    ]
