# Generated by Django 2.0.5 on 2018-05-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplied',
        ),
        migrations.AddField(
            model_name='product',
            name='not_supplied',
            field=models.BooleanField(default=False, help_text='Product will not print on suppliers invoice'),
        ),
    ]
