# Generated by Django 2.0.5 on 2018-05-30 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20180524_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='zincalume_discount_new_south_wales',
            new_name='zincalume_discount_new_south_whales',
        ),
    ]
