# Generated by Django 2.0.5 on 2018-06-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20180530_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_nsw_supplier',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_qld_supplier',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_vic_supplier',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
