# Generated by Django 2.0.5 on 2018-06-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20180619_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='not_supplied',
        ),
        migrations.AddField(
            model_name='product',
            name='packed',
            field=models.BooleanField(default=False, help_text='Packed when ordered to Victoria'),
        ),
    ]
