# Generated by Django 2.0.5 on 2018-06-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20180620_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='product',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
