# Generated by Django 2.0.5 on 2018-06-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20180626_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['my_order']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='the_order',
        ),
        migrations.AddField(
            model_name='product',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
