# Generated by Django 2.0.5 on 2018-07-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20180626_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='standard_shipping',
        ),
        migrations.AddField(
            model_name='product',
            name='postage',
            field=models.BooleanField(default=False, help_text='Sent via postage when order only contains postage items'),
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.BooleanField(default=False, help_text='Sent to site by supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_nsw_supplier',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Lysaght', 'Lysaght'), ('Ampelite', 'Ampelite'), ('MRO', 'MRO'), ('Metroll', 'Metroll'), ('Fletcher', 'Fletcher'), ('Battmans', 'Battmans'), ('Bremick', 'Bremick')], default='Supplier', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_qld_supplier',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Lysaght', 'Lysaght'), ('Ampelite', 'Ampelite'), ('MRO', 'MRO'), ('Metroll', 'Metroll'), ('Fletcher', 'Fletcher'), ('Battmans', 'Battmans'), ('Bremick', 'Bremick')], default='Supplier', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_vic_supplier',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Lysaght', 'Lysaght'), ('Ampelite', 'Ampelite'), ('MRO', 'MRO'), ('Metroll', 'Metroll'), ('Fletcher', 'Fletcher'), ('Battmans', 'Battmans'), ('Bremick', 'Bremick')], default='Supplier', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='packed',
            field=models.BooleanField(default=False, help_text='Packed in-house'),
        ),
    ]
