# Generated by Django 2.0.5 on 2018-07-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20180703_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vic_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='DEFAULT', help_text='Generic name to display in backend', max_length=120, null=True),
        ),
    ]
