# Generated by Django 2.0.5 on 2018-07-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20180703_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_nsw_supplier',
            field=models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Lysaght', 'Lysaght'), ('Ampelite', 'Ampelite'), ('MRO', 'MRO'), ('Metroll', 'Metroll'), ('Fletcher', 'Fletcher'), ('Battmans', 'Battmans'), ('Bremick', 'Bremick')], default='Supplier', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_qld_supplier',
            field=models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Lysaght', 'Lysaght'), ('Ampelite', 'Ampelite'), ('MRO', 'MRO'), ('Metroll', 'Metroll'), ('Fletcher', 'Fletcher'), ('Battmans', 'Battmans'), ('Bremick', 'Bremick')], default='Supplier', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_vic_supplier',
            field=models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Lysaght', 'Lysaght'), ('Ampelite', 'Ampelite'), ('MRO', 'MRO'), ('Metroll', 'Metroll'), ('Fletcher', 'Fletcher'), ('Battmans', 'Battmans'), ('Bremick', 'Bremick')], default='Supplier', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='DEFAULT', help_text='Generic name to display in backend', max_length=120),
        ),
    ]
