# Generated by Django 2.0.5 on 2018-07-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_product_preload_lengths_short_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='length',
            options={'ordering': ['length']},
        ),
    ]
