# Generated by Django 2.0.5 on 2018-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20180712_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='hex_value',
            field=models.CharField(blank=True, help_text='Hex value for colour e.g:  #ff5733', max_length=120, null=True),
        ),
    ]
