# Generated by Django 2.0.5 on 2018-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20181018_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vic_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='zincalume_discount_new_south_wales',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='zincalume_discount_queensland',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
