# Generated by Django 2.0.5 on 2018-12-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_auto_20181022_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_wa_supplier',
            field=models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Lysaght', 'Lysaght'), ('Ampelite', 'Ampelite'), ('MRO', 'MRO'), ('Metroll', 'Metroll'), ('Fletcher', 'Fletcher'), ('Battmans', 'Battmans'), ('Bremick', 'Bremick')], default='Supplier', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wa_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wa_price_per_mm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wa_supplier_per_mm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wa_supplier_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wa_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='zincalume_discount_wa',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=20, null=True),
        ),
    ]
