# Generated by Django 2.0.5 on 2020-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20181205_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='length',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, help_text='Length in metres', max_digits=20, null=True),
        ),
    ]
