# Generated by Django 2.1.7 on 2020-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20200727_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length_steps',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, help_text='Amount between lengths', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_length',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Maximum length in mm', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_length',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='Minimum length in mm', max_digits=20, null=True),
        ),
    ]
