# Generated by Django 2.0.5 on 2019-02-22 03:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=tinymce.models.HTMLField(verbose_name='testimonial'),
        ),
    ]
