# Generated by Django 2.0.5 on 2019-05-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20181205_1544'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_eta',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='email_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid'), ('Delivery ETA', 'Delivery ETA'), ('Changed Delivery Date', 'Changed Delivery Date'), ('Posted', 'Posted'), ('Collection Reminder', 'Collection Reminder'), ('VIC Collection', 'VIC Collection'), ('Pick Up ETA', 'Pick Up ETA'), ('Pick Up Date Change', 'Pick Up Date Change')], default='Delivery ETA', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='flash',
            field=models.CharField(choices=[(' ', ' '), ('Created', 'Created'), ('Ordered', 'Ordered'), ('?', '?'), ('✓', '✓')], default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='flashings_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='order',
            name='last_email',
            field=models.TextField(default='No email has been sent to this customer yet.', max_length=999),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(choices=[(' ', ' '), ('VIC', 'VIC'), ('NSW', 'NSW'), ('QLD', 'QLD'), ('654', 'Delivery'), ('Postage', '427'), ('245', 'Standing Seam'), ('239', 'Inhouse Flashings')], default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='owed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='order',
            name='pack',
            field=models.CharField(choices=[(' ', ' '), ('Created', 'Created'), ('Ordered', 'Ordered'), ('?', '?'), ('✓', '✓')], default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='packing_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[(' ', ' '), ('Standard Post', 'Standard Post'), ('Express Post', 'Express Post'), ('WA Standard Post', 'WA Standard Post'), ('WA Express Post', 'WA Express Post'), ('Pickup', 'Pickup'), ('VIC', 'VIC'), ('NSW', 'NSW'), ('QLD', 'QLD'), ('ACT', 'ACT'), ('TAS', 'TAS'), ('WA', 'WA'), ('NT', 'NT')], default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.CharField(choices=[(' ', ' '), ('Created', 'Created'), ('Ordered', 'Ordered'), ('?', '?'), ('✓', '✓')], default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.CharField(choices=[(' ', ' '), ('Created', 'Created'), ('Ordered', 'Ordered'), ('?', '?'), ('✓', '✓')], default=' ', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='suburb',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_eta',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='additional_drop_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.AdditionalDropDown'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='destination',
            field=models.CharField(blank=True, choices=[('Store', 'Store'), ('Site', 'Site'), ('Flashings', 'Flashings'), ('Stock', 'Stock')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.CharField(blank=True, choices=[(' ', ' '), ('Lysaght', 'Lysaght'), ('Ampelite', 'Ampelite'), ('MRO', 'MRO'), ('Metroll', 'Metroll'), ('Fletcher', 'Fletcher'), ('Battmans', 'Battmans'), ('Bremick', 'Bremick')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='to_be_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='Changes: \n', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Payment Accepted', 'Payment Accepted'), ('Reviewing Order', 'Reviewing Order'), ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Refunded', 'Refunded'), ('Xero Invoice Awaiting Payment', 'Xero Invoice Awaiting Payment'), ('Waiting For Collection', 'Waiting For Collection'), ('Completed By Supplier', 'Completed By Supplier'), ('Completed', 'Completed')], default='Created', max_length=120),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Colour'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Length'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
