# Generated by Django 2.0.5 on 2020-07-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190516_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_instructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
