# Generated by Django 2.1.7 on 2020-08-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='length',
            new_name='product_length',
        ),
    ]
