# Generated by Django 2.1.7 on 2020-08-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=200),
        ),
    ]
