# Generated by Django 2.1.7 on 2020-09-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200903_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=200, null=True),
        ),
    ]
